# Generated by Django 5.0.1 on 2024-08-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_appliedapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedapplication",
            name="has_applied",
            field=models.BooleanField(default=False),
        ),
    ]
