# Generated by Django 5.0.1 on 2024-08-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rename_admin_user_is_cse_remove_user_dashboard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="drives",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
