# Generated by Django 5.1 on 2024-08-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_documents_alter_user_batch_alter_user_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
