# Generated by Django 5.0.1 on 2024-08-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_reg_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attempted',
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
