# Generated by Django 5.0.1 on 2024-08-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_appliedapplication'),
        ('user', '0007_user_job_application_alter_user_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job_application',
        ),
        migrations.AlterField(
            model_name='user',
            name='documents',
            field=models.ManyToManyField(related_name='users', to='home.document'),
        ),
    ]
